import { notFound } from 'next/navigation'
import { Suspense } from 'react'
import type { Metadata } from 'next'
import Link from 'next/link'
import { getCaseBySlug } from '@/lib/utils'
import { CASES } from '@/lib/constants'
import type { Profile } from '@/lib/supabase/types'
import { TalentCard } from '@/components/talent/TalentCard'
import { FilterBar } from '@/components/cases/FilterBar'
import { createClient } from '@/lib/supabase/server'

// ─── Static params ─────────────────────────────────────────────────────────────

export function generateStaticParams() {
  return CASES.map((c) => ({ case: c.slug }))
}

// ─── Metadata ─────────────────────────────────────────────────────────────────

export async function generateMetadata({
  params,
  searchParams,
}: {
  params: Promise<{ case: string }>
  searchParams: Promise<{ ville?: string }>
}): Promise<Metadata> {
  const { case: caseSlug } = await params
  const { ville } = await searchParams
  const caseData = getCaseBySlug(caseSlug)

  if (!caseData) {
    return { title: 'Case introuvable' }
  }

  const cityPart = ville ? ` à ${ville}` : ' en France'
  const titleMap: Record<string, string> = {
    beaute: `Coiffeuses, ongles & maquillage${cityPart}`,
    maison: `Bricolage & montage de meubles${cityPart}`,
    couture: `Couturières & retouches sur-mesure${cityPart}`,
    saveurs: `Chefs à domicile & traiteurs${cityPart}`,
    savoir: `Cours de langues & soutien scolaire${cityPart}`,
    zen: `Massages & soins bien-être${cityPart}`,
    assistance: `Aide administrative & numérique${cityPart}`,
  }

  const title = titleMap[caseSlug] ?? `${caseData.label}${cityPart}`

  return {
    title,
    description: `${caseData.description}. Trouvez des professionnels de la communauté${cityPart} sur Talents d'Afrique.`,
    openGraph: {
      title: `${title} | Talents d'Afrique`,
      description: `${caseData.description}. Talents vérifiés par la communauté.`,
    },
  }
}

// ─── Mock data per case ────────────────────────────────────────────────────────

const mockTalentsByCase: Record<string, Array<Partial<Profile> & { id: string; name: string; city: string; trust_score: number; review_count: number; status: 'parraine' | 'observation'; is_talent: boolean; is_admin: boolean; sub_services: string[]; availability: Record<string, { start: string; end: string }>; photos: string[]; kory_balance: number; parrain_code: string; created_at: string; updated_at: string }>> = {
  beaute: [
    {
      id: 'mock-beaute-1',
      name: 'Aminata Diallo',
      city: 'Paris',
      bio: 'Coiffeuse spécialisée en tresses africaines depuis 8 ans. Je me déplace à domicile dans tout Paris et la petite couronne. Tresses collées, locks, perruques lace wig — je maîtrise toutes les techniques.',
      case_slug: 'beaute',
      sub_services: ['Coiffure (braids, locks, perruques)', 'Tresses collées', 'Locks'],
      availability: {
        Samedi: { start: '09:00', end: '19:00' },
        Dimanche: { start: '10:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/aminata/400/300'],
      status: 'parraine',
      trust_score: 4.8,
      review_count: 23,
      parrain_code: 'AMINA001',
      kory_balance: 45,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-01-15T10:00:00Z',
      updated_at: '2024-06-01T12:00:00Z',
    },
    {
      id: 'mock-beaute-2',
      name: 'Mariama Baldé',
      city: 'Lyon',
      bio: 'Ongles en gel, résine et nail art afro-inspiré. 5 ans d\'expérience en salon et à domicile. Chaque pose est une œuvre d\'art adaptée à votre style.',
      case_slug: 'beaute',
      sub_services: ['Onglerie (gel, résine, nail art)', 'Nail art'],
      availability: {
        Lundi: { start: '10:00', end: '18:00' },
        Mardi: { start: '10:00', end: '18:00' },
        Mercredi: { start: '10:00', end: '18:00' },
        Samedi: { start: '09:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/mariama/400/300'],
      status: 'parraine',
      trust_score: 4.9,
      review_count: 41,
      parrain_code: 'MARIB002',
      kory_balance: 62,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-02-10T10:00:00Z',
      updated_at: '2024-06-10T12:00:00Z',
    },
    {
      id: 'mock-beaute-3',
      name: 'Fatou Camara',
      city: 'Paris',
      bio: 'Maquilleuse professionnelle spécialisée dans la mise en valeur des peaux noires et métissées. Mariages, anniversaires, shootings photo — votre beauté naturelle sublimée.',
      case_slug: 'beaute',
      sub_services: ['Maquillage (MUA)', 'Épilation'],
      availability: {
        Vendredi: { start: '14:00', end: '20:00' },
        Samedi: { start: '08:00', end: '20:00' },
        Dimanche: { start: '10:00', end: '18:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 4.7,
      review_count: 17,
      parrain_code: 'FATCA003',
      kory_balance: 28,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-03-05T10:00:00Z',
      updated_at: '2024-06-05T12:00:00Z',
    },
    {
      id: 'mock-beaute-4',
      name: 'Binta Kouyaté',
      city: 'Marseille',
      bio: 'Spécialiste de la coiffure naturelle et des soins capillaires. Twist, vanilles, revers, braid out — je prends soin de votre chevelure avec des produits 100% naturels.',
      case_slug: 'beaute',
      sub_services: ['Coiffure (braids, locks, perruques)'],
      availability: {
        Mercredi: { start: '10:00', end: '19:00' },
        Jeudi: { start: '10:00', end: '19:00' },
        Samedi: { start: '09:00', end: '18:00' },
      },
      photos: ['https://picsum.photos/seed/binta/400/300'],
      status: 'observation',
      trust_score: 4.4,
      review_count: 6,
      parrain_code: 'BINTK004',
      kory_balance: 12,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-04-20T10:00:00Z',
      updated_at: '2024-06-15T12:00:00Z',
    },
    {
      id: 'mock-beaute-5',
      name: 'Ndeye Sow',
      city: 'Paris',
      bio: 'Prothésiste ongulaire certifiée avec 6 ans de pratique. Spécialiste des nail art africains et des poses longue durée. Hygiène irréprochable, matériel professionnel.',
      case_slug: 'beaute',
      sub_services: ['Onglerie (gel, résine, nail art)'],
      availability: {
        Mardi: { start: '09:00', end: '19:00' },
        Jeudi: { start: '09:00', end: '19:00' },
        Samedi: { start: '10:00', end: '18:00' },
        Dimanche: { start: '11:00', end: '17:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 5.0,
      review_count: 54,
      parrain_code: 'NDEYS005',
      kory_balance: 88,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-11-01T10:00:00Z',
      updated_at: '2024-06-20T12:00:00Z',
    },
    {
      id: 'mock-beaute-6',
      name: 'Rokhaya Mbaye',
      city: 'Île-de-France',
      bio: 'Esthéticienne et coiffeuse polyvalente. Épilation au fil, cire orientale, soins du visage et coiffure afro. Je me déplace à votre domicile dans toute l\'Île-de-France.',
      case_slug: 'beaute',
      sub_services: ['Épilation', 'Maquillage (MUA)', 'Coiffure (braids, locks, perruques)'],
      availability: {
        Lundi: { start: '09:00', end: '17:00' },
        Mercredi: { start: '09:00', end: '17:00' },
        Vendredi: { start: '09:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/rokhaya/400/300'],
      status: 'observation',
      trust_score: 4.2,
      review_count: 3,
      parrain_code: 'ROKMB006',
      kory_balance: 10,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-05-12T10:00:00Z',
      updated_at: '2024-06-18T12:00:00Z',
    },
  ],

  maison: [
    {
      id: 'mock-maison-1',
      name: 'Moussa Traoré',
      city: 'Paris',
      bio: 'Artisan polyvalent avec 10 ans d\'expérience dans le bâtiment. Montage IKEA, petite plomberie, électricité courante, peinture — je règle vos problèmes rapidement et proprement.',
      case_slug: 'maison',
      sub_services: ['Montage de meubles (IKEA, etc.)', 'Petit bricolage'],
      availability: {
        Lundi: { start: '08:00', end: '18:00' },
        Mardi: { start: '08:00', end: '18:00' },
        Mercredi: { start: '08:00', end: '18:00' },
        Jeudi: { start: '08:00', end: '18:00' },
        Vendredi: { start: '08:00', end: '18:00' },
      },
      photos: ['https://picsum.photos/seed/moussa/400/300'],
      status: 'parraine',
      trust_score: 4.9,
      review_count: 38,
      parrain_code: 'MOUTR001',
      kory_balance: 71,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-10-01T10:00:00Z',
      updated_at: '2024-06-01T12:00:00Z',
    },
    {
      id: 'mock-maison-2',
      name: 'Ibrahima Koné',
      city: 'Lyon',
      bio: 'Déménagement, montage de meubles, décoration intérieure. Sérieux, ponctuel et soigneux avec vos affaires. Disponible weekends et soirées selon planning.',
      case_slug: 'maison',
      sub_services: ['Aide au déménagement', 'Montage de meubles (IKEA, etc.)'],
      availability: {
        Samedi: { start: '08:00', end: '18:00' },
        Dimanche: { start: '09:00', end: '16:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 4.6,
      review_count: 12,
      parrain_code: 'IBRKN002',
      kory_balance: 25,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-01-20T10:00:00Z',
      updated_at: '2024-05-28T12:00:00Z',
    },
    {
      id: 'mock-maison-3',
      name: 'Seydou Coulibaly',
      city: 'Marseille',
      bio: 'Décorateur d\'intérieur autodidacte passionné. Je transforme vos espaces avec des touches afro-contemporaines. Tissu wax en déco, mobilier custom, ambiance unique garantie.',
      case_slug: 'maison',
      sub_services: ['Décoration intérieure', 'Montage de meubles (IKEA, etc.)'],
      availability: {
        Jeudi: { start: '14:00', end: '19:00' },
        Vendredi: { start: '14:00', end: '19:00' },
        Samedi: { start: '10:00', end: '18:00' },
      },
      photos: ['https://picsum.photos/seed/seydou/400/300'],
      status: 'observation',
      trust_score: 4.3,
      review_count: 5,
      parrain_code: 'SEYCL003',
      kory_balance: 10,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-04-05T10:00:00Z',
      updated_at: '2024-06-10T12:00:00Z',
    },
    {
      id: 'mock-maison-4',
      name: 'Oumar Diarra',
      city: 'Paris',
      bio: 'Électricien qualifié, petits travaux de plomberie, pose de luminaires et de prises. Intervention rapide, devis honnête. Je suis le "MacGyver" de la diaspora !',
      case_slug: 'maison',
      sub_services: ['Petit bricolage'],
      availability: {
        Mercredi: { start: '09:00', end: '18:00' },
        Samedi: { start: '09:00', end: '18:00' },
        Dimanche: { start: '10:00', end: '16:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 4.8,
      review_count: 29,
      parrain_code: 'OUMDI004',
      kory_balance: 53,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-12-15T10:00:00Z',
      updated_at: '2024-06-12T12:00:00Z',
    },
    {
      id: 'mock-maison-5',
      name: 'Adama Touré',
      city: 'Toulouse',
      bio: 'Aide au déménagement, montage et démontage de meubles. Camionnette disponible pour petits déménagements locaux. Tarifs adaptés à nos réalités communautaires.',
      case_slug: 'maison',
      sub_services: ['Aide au déménagement', 'Montage de meubles (IKEA, etc.)'],
      availability: {
        Lundi: { start: '08:00', end: '17:00' },
        Vendredi: { start: '08:00', end: '17:00' },
        Samedi: { start: '08:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/adama/400/300'],
      status: 'parraine',
      trust_score: 4.5,
      review_count: 16,
      parrain_code: 'ADATO005',
      kory_balance: 33,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-02-20T10:00:00Z',
      updated_at: '2024-06-08T12:00:00Z',
    },
    {
      id: 'mock-maison-6',
      name: 'Lamine Sarr',
      city: 'Bordeaux',
      bio: 'Peintre en bâtiment et décorateur. Refaire une pièce, rafraîchir un appartement, appliquer du papier peint — je maîtrise tout. Travail soigné, délais respectés.',
      case_slug: 'maison',
      sub_services: ['Petit bricolage', 'Décoration intérieure'],
      availability: {
        Mardi: { start: '09:00', end: '17:00' },
        Mercredi: { start: '09:00', end: '17:00' },
        Jeudi: { start: '09:00', end: '17:00' },
        Samedi: { start: '09:00', end: '15:00' },
      },
      photos: [],
      status: 'observation',
      trust_score: 4.2,
      review_count: 2,
      parrain_code: 'LAMSA006',
      kory_balance: 10,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-05-30T10:00:00Z',
      updated_at: '2024-06-20T12:00:00Z',
    },
  ],

  couture: [
    {
      id: 'mock-couture-1',
      name: 'Kadiatou Bah',
      city: 'Paris',
      bio: 'Couturière créatrice spécialisée dans les tenues africaines sur-mesure. Wax, Bazin, Kente — je crée des pièces uniques qui célèbrent votre heritage. Retouches rapides aussi.',
      case_slug: 'couture',
      sub_services: ['Création sur-mesure (Wax, Bazin, Pagne)', 'Retouches vêtements'],
      availability: {
        Mardi: { start: '10:00', end: '19:00' },
        Jeudi: { start: '10:00', end: '19:00' },
        Samedi: { start: '09:00', end: '18:00' },
      },
      photos: ['https://picsum.photos/seed/kadiatou/400/300'],
      status: 'parraine',
      trust_score: 4.9,
      review_count: 47,
      parrain_code: 'KADBA001',
      kory_balance: 78,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-09-01T10:00:00Z',
      updated_at: '2024-06-01T12:00:00Z',
    },
    {
      id: 'mock-couture-2',
      name: 'Aïssatou Diop',
      city: 'Lyon',
      bio: 'Retoucheuse expérimentée (15 ans de métier). Ourlets, cintrage, rallongement, réparations — je redonne vie à vos vêtements. Délai 48h pour les retouches simples.',
      case_slug: 'couture',
      sub_services: ['Retouches vêtements', 'Couture générale'],
      availability: {
        Lundi: { start: '09:00', end: '17:00' },
        Mercredi: { start: '09:00', end: '17:00' },
        Vendredi: { start: '09:00', end: '17:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 4.8,
      review_count: 62,
      parrain_code: 'AISSDI002',
      kory_balance: 92,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-08-15T10:00:00Z',
      updated_at: '2024-06-05T12:00:00Z',
    },
    {
      id: 'mock-couture-3',
      name: 'Mariam Sylla',
      city: 'Marseille',
      bio: 'Brodeuse artisanale et couturière. Broderies dorées sur Bazin pour des tenues de mariage et de cérémonie inoubliables. Chaque broderie raconte une histoire.',
      case_slug: 'couture',
      sub_services: ['Broderie', 'Création sur-mesure (Wax, Bazin, Pagne)'],
      availability: {
        Samedi: { start: '10:00', end: '18:00' },
        Dimanche: { start: '11:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/mariam/400/300'],
      status: 'parraine',
      trust_score: 5.0,
      review_count: 28,
      parrain_code: 'MARSY003',
      kory_balance: 55,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-01-10T10:00:00Z',
      updated_at: '2024-06-15T12:00:00Z',
    },
    {
      id: 'mock-couture-4',
      name: 'Oumou Konaté',
      city: 'Paris',
      bio: 'Styliste et couturière prêt-à-porter africain. Je crée des collections capsules et des pièces uniques pour les femmes qui assument leur identité avec élégance.',
      case_slug: 'couture',
      sub_services: ['Création sur-mesure (Wax, Bazin, Pagne)', 'Couture générale'],
      availability: {
        Jeudi: { start: '14:00', end: '20:00' },
        Vendredi: { start: '14:00', end: '20:00' },
        Samedi: { start: '10:00', end: '18:00' },
      },
      photos: [],
      status: 'observation',
      trust_score: 4.4,
      review_count: 7,
      parrain_code: 'OUMKN004',
      kory_balance: 14,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-03-25T10:00:00Z',
      updated_at: '2024-06-10T12:00:00Z',
    },
    {
      id: 'mock-couture-5',
      name: 'Hawa Traoré',
      city: 'Île-de-France',
      bio: 'Couturière généraliste et retoucheuse. Grande habitude des tissus africains mais aussi des matières occidentales. Tarifs honnêtes, travail de qualité.',
      case_slug: 'couture',
      sub_services: ['Couture générale', 'Retouches vêtements'],
      availability: {
        Mardi: { start: '09:00', end: '18:00' },
        Mercredi: { start: '09:00', end: '18:00' },
        Samedi: { start: '09:00', end: '16:00' },
      },
      photos: ['https://picsum.photos/seed/hawa/400/300'],
      status: 'parraine',
      trust_score: 4.6,
      review_count: 19,
      parrain_code: 'HAWTR005',
      kory_balance: 37,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-02-01T10:00:00Z',
      updated_at: '2024-06-08T12:00:00Z',
    },
    {
      id: 'mock-couture-6',
      name: 'Coumba Faye',
      city: 'Nantes',
      bio: 'Petite atelier de couture spécialisé dans les tenues de baptêmes et mariages africains. Je crée des ensembles complets (boubou, gele, accessoires) pour toute la famille.',
      case_slug: 'couture',
      sub_services: ['Création sur-mesure (Wax, Bazin, Pagne)', 'Broderie'],
      availability: {
        Lundi: { start: '10:00', end: '18:00' },
        Vendredi: { start: '10:00', end: '18:00' },
        Samedi: { start: '09:00', end: '17:00' },
      },
      photos: [],
      status: 'observation',
      trust_score: 4.3,
      review_count: 4,
      parrain_code: 'COUMFA006',
      kory_balance: 10,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-05-01T10:00:00Z',
      updated_at: '2024-06-20T12:00:00Z',
    },
  ],

  saveurs: [
    {
      id: 'mock-saveurs-1',
      name: 'Awa Coulibaly',
      city: 'Paris',
      bio: 'Chef cuisinière professionnelle, je propose des dîners à domicile et du batch cooking africain. Thiéboudienne, mafé, yassa, ndolé — je cuisine l\'Afrique de l\'Ouest et du Centre avec amour.',
      case_slug: 'saveurs',
      sub_services: ['Chef à domicile', 'Batch cooking hebdomadaire'],
      availability: {
        Mercredi: { start: '10:00', end: '18:00' },
        Jeudi: { start: '10:00', end: '18:00' },
        Samedi: { start: '09:00', end: '20:00' },
      },
      photos: ['https://picsum.photos/seed/awa/400/300'],
      status: 'parraine',
      trust_score: 4.9,
      review_count: 35,
      parrain_code: 'AWACL001',
      kory_balance: 66,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-11-01T10:00:00Z',
      updated_at: '2024-06-01T12:00:00Z',
    },
    {
      id: 'mock-saveurs-2',
      name: 'Souleymane Ndiaye',
      city: 'Lyon',
      bio: 'Traiteur événementiel spécialisé dans la cuisine sénégalaise et malienne. Baptêmes, mariages, anniversaires — je prends en charge tout le volet culinaire de votre événement.',
      case_slug: 'saveurs',
      sub_services: ['Traiteur événementiel', 'Chef à domicile'],
      availability: {
        Vendredi: { start: '08:00', end: '20:00' },
        Samedi: { start: '08:00', end: '22:00' },
        Dimanche: { start: '10:00', end: '20:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 4.8,
      review_count: 22,
      parrain_code: 'SOULND002',
      kory_balance: 44,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-01-05T10:00:00Z',
      updated_at: '2024-05-30T12:00:00Z',
    },
    {
      id: 'mock-saveurs-3',
      name: 'Binta Camara',
      city: 'Paris',
      bio: 'Cours de cuisine africaine pour débutants et confirmés. Apprenez à cuisiner le thiébou djeun, la sauce arachide, le jollof rice. Sessions en groupe ou individuelles.',
      case_slug: 'saveurs',
      sub_services: ['Cours de cuisine', 'Batch cooking hebdomadaire'],
      availability: {
        Samedi: { start: '10:00', end: '14:00' },
        Dimanche: { start: '11:00', end: '15:00' },
      },
      photos: ['https://picsum.photos/seed/bintac/400/300'],
      status: 'parraine',
      trust_score: 5.0,
      review_count: 18,
      parrain_code: 'BINCA003',
      kory_balance: 40,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-02-15T10:00:00Z',
      updated_at: '2024-06-12T12:00:00Z',
    },
    {
      id: 'mock-saveurs-4',
      name: 'Djibril Touré',
      city: 'Marseille',
      bio: 'Batch cooking hebdomadaire, je prépare vos repas de la semaine chez vous. Cuisine saine, équilibrée et africaine. Fini les galères de semaine — mangez bien tous les jours !',
      case_slug: 'saveurs',
      sub_services: ['Batch cooking hebdomadaire'],
      availability: {
        Lundi: { start: '09:00', end: '16:00' },
        Mardi: { start: '09:00', end: '16:00' },
      },
      photos: [],
      status: 'observation',
      trust_score: 4.5,
      review_count: 8,
      parrain_code: 'DJIBT004',
      kory_balance: 18,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-03-10T10:00:00Z',
      updated_at: '2024-06-15T12:00:00Z',
    },
    {
      id: 'mock-saveurs-5',
      name: 'Rokiatou Sidibé',
      city: 'Bordeaux',
      bio: 'Cuisinière traiteur, je propose des menus africains sur commande pour emporter ou livrés. Plats congolais, camerounais, ivoiriens — la diversité de l\'Afrique dans votre assiette.',
      case_slug: 'saveurs',
      sub_services: ['Traiteur événementiel', 'Batch cooking hebdomadaire'],
      availability: {
        Mercredi: { start: '10:00', end: '17:00' },
        Jeudi: { start: '10:00', end: '17:00' },
        Vendredi: { start: '10:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/rokiatou/400/300'],
      status: 'parraine',
      trust_score: 4.7,
      review_count: 13,
      parrain_code: 'ROKISI005',
      kory_balance: 29,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-02-28T10:00:00Z',
      updated_at: '2024-06-10T12:00:00Z',
    },
    {
      id: 'mock-saveurs-6',
      name: 'Mamadou Keita',
      city: 'Lille',
      bio: 'Chef cuisinier malien, spécialiste du Tô, du Foutou et des sauces traditionnelles. Je me déplace à domicile pour vous faire vivre une expérience gastronomique africaine authentique.',
      case_slug: 'saveurs',
      sub_services: ['Chef à domicile', 'Cours de cuisine'],
      availability: {
        Samedi: { start: '11:00', end: '20:00' },
        Dimanche: { start: '11:00', end: '18:00' },
      },
      photos: [],
      status: 'observation',
      trust_score: 4.2,
      review_count: 3,
      parrain_code: 'MAMKE006',
      kory_balance: 10,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-05-20T10:00:00Z',
      updated_at: '2024-06-20T12:00:00Z',
    },
  ],

  savoir: [
    {
      id: 'mock-savoir-1',
      name: 'Khouma Diallo',
      city: 'Paris',
      bio: 'Professeur de wolof, pulaar et français pour allophones. Je transmet les langues africaines de la diaspora avec pédagogie et passion. Sessions individuelles ou en famille.',
      case_slug: 'savoir',
      sub_services: ['Cours de langues africaines'],
      availability: {
        Mercredi: { start: '14:00', end: '19:00' },
        Samedi: { start: '09:00', end: '17:00' },
        Dimanche: { start: '10:00', end: '15:00' },
      },
      photos: ['https://picsum.photos/seed/khouma/400/300'],
      status: 'parraine',
      trust_score: 4.9,
      review_count: 31,
      parrain_code: 'KHOUDI001',
      kory_balance: 58,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-10-15T10:00:00Z',
      updated_at: '2024-06-01T12:00:00Z',
    },
    {
      id: 'mock-savoir-2',
      name: 'Fatoumata Kourouma',
      city: 'Lyon',
      bio: 'Enseignante diplômée, spécialiste du soutien scolaire de la CP au lycée. Maths, français, histoire — je remotive les élèves et leur redonne confiance en eux.',
      case_slug: 'savoir',
      sub_services: ['Soutien scolaire'],
      availability: {
        Mardi: { start: '16:00', end: '20:00' },
        Jeudi: { start: '16:00', end: '20:00' },
        Samedi: { start: '09:00', end: '13:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 5.0,
      review_count: 44,
      parrain_code: 'FATKO002',
      kory_balance: 80,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-09-20T10:00:00Z',
      updated_at: '2024-06-05T12:00:00Z',
    },
    {
      id: 'mock-savoir-3',
      name: 'Alpha Condé',
      city: 'Paris',
      bio: 'Percussionniste et musicien traditionnel guinéen. J\'enseigne le djembé, le balafon et les rythmes d\'Afrique de l\'Ouest. Cours adaptés à tous les niveaux.',
      case_slug: 'savoir',
      sub_services: ['Initiation aux instruments', 'Initiation culturelle'],
      availability: {
        Mercredi: { start: '14:00', end: '20:00' },
        Samedi: { start: '10:00', end: '18:00' },
      },
      photos: ['https://picsum.photos/seed/alpha/400/300'],
      status: 'parraine',
      trust_score: 4.8,
      review_count: 19,
      parrain_code: 'ALPHCO003',
      kory_balance: 42,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-01-25T10:00:00Z',
      updated_at: '2024-06-10T12:00:00Z',
    },
    {
      id: 'mock-savoir-4',
      name: 'Nafi Dembélé',
      city: 'Marseille',
      bio: 'Guide culturel et historienne spécialisée dans les civilisations africaines. Ateliers d\'initiation à l\'histoire de l\'Afrique pour enfants et adultes. Remettons nos racines au cœur de l\'éducation.',
      case_slug: 'savoir',
      sub_services: ['Initiation culturelle'],
      availability: {
        Samedi: { start: '10:00', end: '16:00' },
        Dimanche: { start: '11:00', end: '15:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 4.7,
      review_count: 11,
      parrain_code: 'NAFIDE004',
      kory_balance: 26,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-02-12T10:00:00Z',
      updated_at: '2024-06-15T12:00:00Z',
    },
    {
      id: 'mock-savoir-5',
      name: 'Samba Gueye',
      city: 'Île-de-France',
      bio: 'Professeur de mathématiques niveau lycée et prépa. Bac, BTS, concours — je prépare les jeunes de la diaspora à décrocher les meilleures formations. La réussite, c\'est notre fierté.',
      case_slug: 'savoir',
      sub_services: ['Soutien scolaire'],
      availability: {
        Lundi: { start: '17:00', end: '21:00' },
        Mercredi: { start: '14:00', end: '20:00' },
        Vendredi: { start: '17:00', end: '21:00' },
        Samedi: { start: '10:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/samba/400/300'],
      status: 'observation',
      trust_score: 4.4,
      review_count: 6,
      parrain_code: 'SAMBGU005',
      kory_balance: 14,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-04-01T10:00:00Z',
      updated_at: '2024-06-18T12:00:00Z',
    },
    {
      id: 'mock-savoir-6',
      name: 'Assita Ouédraogo',
      city: 'Rennes',
      bio: 'Diplômée en langues, j\'enseigne le mooré (langue burkinabée), le bambara et propose des initiations à la culture sahélienne. Passeurs de mémoire, gardons nos langues vivantes.',
      case_slug: 'savoir',
      sub_services: ['Cours de langues africaines', 'Initiation culturelle'],
      availability: {
        Samedi: { start: '09:00', end: '18:00' },
        Dimanche: { start: '10:00', end: '16:00' },
      },
      photos: [],
      status: 'observation',
      trust_score: 4.3,
      review_count: 4,
      parrain_code: 'ASSITOU006',
      kory_balance: 10,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-04-20T10:00:00Z',
      updated_at: '2024-06-20T12:00:00Z',
    },
  ],

  zen: [
    {
      id: 'mock-zen-1',
      name: 'Bineta Ndoye',
      city: 'Paris',
      bio: 'Masseuse traditionnelle sénégalaise, certifiée en massage bien-être. Massage beurre de karité, massage aux huiles essentielles africaines, drainage lymphatique. Déplacement à domicile.',
      case_slug: 'zen',
      sub_services: ['Massages traditionnels', 'Soins capillaires naturels'],
      availability: {
        Mardi: { start: '10:00', end: '19:00' },
        Jeudi: { start: '10:00', end: '19:00' },
        Samedi: { start: '09:00', end: '18:00' },
      },
      photos: ['https://picsum.photos/seed/bineta/400/300'],
      status: 'parraine',
      trust_score: 4.9,
      review_count: 36,
      parrain_code: 'BINETND001',
      kory_balance: 67,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-10-01T10:00:00Z',
      updated_at: '2024-06-01T12:00:00Z',
    },
    {
      id: 'mock-zen-2',
      name: 'Yaye Astou Fall',
      city: 'Lyon',
      bio: 'Herboriste et naturopathe spécialisée dans les plantes africaines médicinales. Je crée des produits naturels sur-mesure : tisanes, huiles, savons noirs. Conseils bien-être holistique.',
      case_slug: 'zen',
      sub_services: ['Préparation de produits naturels', 'Conseils en bien-être'],
      availability: {
        Mercredi: { start: '10:00', end: '17:00' },
        Samedi: { start: '10:00', end: '16:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 4.7,
      review_count: 14,
      parrain_code: 'YAYEAF002',
      kory_balance: 31,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-01-20T10:00:00Z',
      updated_at: '2024-06-08T12:00:00Z',
    },
    {
      id: 'mock-zen-3',
      name: 'Maimouna Diallo',
      city: 'Paris',
      bio: 'Spécialiste des soins capillaires naturels pour cheveux afro. Traitements kératine naturelle, soin au beurre de karité, lait de coco. Retrouvez des cheveux sains et brillants.',
      case_slug: 'zen',
      sub_services: ['Soins capillaires naturels'],
      availability: {
        Vendredi: { start: '14:00', end: '20:00' },
        Samedi: { start: '09:00', end: '19:00' },
        Dimanche: { start: '10:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/maimouna/400/300'],
      status: 'parraine',
      trust_score: 4.8,
      review_count: 21,
      parrain_code: 'MAIMDI003',
      kory_balance: 45,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-02-05T10:00:00Z',
      updated_at: '2024-06-12T12:00:00Z',
    },
    {
      id: 'mock-zen-4',
      name: 'Penda Niang',
      city: 'Marseille',
      bio: 'Yoga africain et méditation guidée. J\'intègre des éléments de spiritualité africaine dans ma pratique du yoga. Retrouvez l\'équilibre corps-esprit avec des techniques ancestrales.',
      case_slug: 'zen',
      sub_services: ['Conseils en bien-être', 'Massages traditionnels'],
      availability: {
        Lundi: { start: '07:00', end: '10:00' },
        Mercredi: { start: '07:00', end: '10:00' },
        Samedi: { start: '08:00', end: '12:00' },
      },
      photos: [],
      status: 'observation',
      trust_score: 4.4,
      review_count: 5,
      parrain_code: 'PENDNI004',
      kory_balance: 12,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-04-01T10:00:00Z',
      updated_at: '2024-06-15T12:00:00Z',
    },
    {
      id: 'mock-zen-5',
      name: 'Chérif Barry',
      city: 'Île-de-France',
      bio: 'Réflexologue et masseur sportif. Massage thaï, réflexologie plantaire, massage récupération. Idéal après le sport ou pour soulager le stress du quotidien.',
      case_slug: 'zen',
      sub_services: ['Massages traditionnels'],
      availability: {
        Lundi: { start: '10:00', end: '20:00' },
        Mardi: { start: '10:00', end: '20:00' },
        Samedi: { start: '09:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/cherif/400/300'],
      status: 'parraine',
      trust_score: 4.6,
      review_count: 16,
      parrain_code: 'CHERBA005',
      kory_balance: 35,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-02-18T10:00:00Z',
      updated_at: '2024-06-10T12:00:00Z',
    },
    {
      id: 'mock-zen-6',
      name: 'Kadija Sanogo',
      city: 'Nantes',
      bio: 'Préparatrice de produits naturels africains : savon noir au karité, huile de baobab, shea butter pur. Je vends aussi des formules bien-être personnalisées selon votre profil.',
      case_slug: 'zen',
      sub_services: ['Préparation de produits naturels', 'Conseils en bien-être'],
      availability: {
        Mercredi: { start: '10:00', end: '18:00' },
        Jeudi: { start: '10:00', end: '18:00' },
        Samedi: { start: '10:00', end: '16:00' },
      },
      photos: [],
      status: 'observation',
      trust_score: 4.2,
      review_count: 3,
      parrain_code: 'KADISA006',
      kory_balance: 10,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-05-15T10:00:00Z',
      updated_at: '2024-06-20T12:00:00Z',
    },
  ],

  assistance: [
    {
      id: 'mock-assistance-1',
      name: 'Ibou Diallo',
      city: 'Paris',
      bio: 'Juriste et conseiller administratif. J\'aide la communauté avec les dossiers CAF, préfecture, titre de séjour, naturalisation. Connaissance approfondie des démarches françaises.',
      case_slug: 'assistance',
      sub_services: ['Aide aux dossiers administratifs', 'Rédaction de courriers'],
      availability: {
        Mardi: { start: '18:00', end: '21:00' },
        Jeudi: { start: '18:00', end: '21:00' },
        Samedi: { start: '09:00', end: '15:00' },
      },
      photos: ['https://picsum.photos/seed/ibou/400/300'],
      status: 'parraine',
      trust_score: 4.9,
      review_count: 52,
      parrain_code: 'IBOUDIAL001',
      kory_balance: 95,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-08-01T10:00:00Z',
      updated_at: '2024-06-01T12:00:00Z',
    },
    {
      id: 'mock-assistance-2',
      name: 'Astou Ndoye',
      city: 'Lyon',
      bio: 'Traductrice assermentée français-wolof-anglais. Traduction de documents officiels, interprétariat lors de rendez-vous médicaux ou administratifs. Disponible en présentiel et en visio.',
      case_slug: 'assistance',
      sub_services: ['Traduction'],
      availability: {
        Lundi: { start: '09:00', end: '17:00' },
        Mercredi: { start: '09:00', end: '17:00' },
        Vendredi: { start: '09:00', end: '17:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 4.8,
      review_count: 27,
      parrain_code: 'ASTOND002',
      kory_balance: 53,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-01-10T10:00:00Z',
      updated_at: '2024-06-05T12:00:00Z',
    },
    {
      id: 'mock-assistance-3',
      name: 'Papiss Cissé',
      city: 'Marseille',
      bio: 'Formateur en informatique et assistant numérique. Smartphones, ordinateurs, réseaux sociaux, applications — j\'accompagne les parents et seniors de la communauté dans leur transition numérique.',
      case_slug: 'assistance',
      sub_services: ['Assistance numérique'],
      availability: {
        Mercredi: { start: '14:00', end: '19:00' },
        Samedi: { start: '10:00', end: '18:00' },
        Dimanche: { start: '11:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/papiss/400/300'],
      status: 'parraine',
      trust_score: 4.7,
      review_count: 20,
      parrain_code: 'PAPICI003',
      kory_balance: 41,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-02-20T10:00:00Z',
      updated_at: '2024-06-10T12:00:00Z',
    },
    {
      id: 'mock-assistance-4',
      name: 'Mame Diarra Bousso',
      city: 'Paris',
      bio: 'Rédactrice professionnelle spécialisée dans les lettres de motivation, CV, courriers officiels et recours administratifs. J\'aide la diaspora à s\'exprimer avec impact à l\'écrit.',
      case_slug: 'assistance',
      sub_services: ['Rédaction de courriers'],
      availability: {
        Lundi: { start: '10:00', end: '18:00' },
        Mardi: { start: '10:00', end: '18:00' },
        Jeudi: { start: '10:00', end: '18:00' },
      },
      photos: [],
      status: 'parraine',
      trust_score: 4.9,
      review_count: 33,
      parrain_code: 'MAMEDB004',
      kory_balance: 62,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2023-12-01T10:00:00Z',
      updated_at: '2024-06-12T12:00:00Z',
    },
    {
      id: 'mock-assistance-5',
      name: 'Moustapha Sy',
      city: 'Strasbourg',
      bio: 'Conseiller en démarches administratives et création d\'entreprise. Immatriculation, micro-entreprise, KBIS — je guide les entrepreneurs de la diaspora pas à pas.',
      case_slug: 'assistance',
      sub_services: ['Aide aux dossiers administratifs'],
      availability: {
        Vendredi: { start: '18:00', end: '21:00' },
        Samedi: { start: '09:00', end: '17:00' },
      },
      photos: ['https://picsum.photos/seed/moustapha/400/300'],
      status: 'observation',
      trust_score: 4.5,
      review_count: 9,
      parrain_code: 'MOUSSY005',
      kory_balance: 20,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-03-15T10:00:00Z',
      updated_at: '2024-06-18T12:00:00Z',
    },
    {
      id: 'mock-assistance-6',
      name: 'Rokhaya Gueye',
      city: 'Nantes',
      bio: 'Interprète et médiatrice culturelle. Je facilite la communication entre la communauté africaine et les institutions françaises (hôpitaux, écoles, administrations).',
      case_slug: 'assistance',
      sub_services: ['Traduction', 'Aide aux dossiers administratifs'],
      availability: {
        Lundi: { start: '09:00', end: '17:00' },
        Jeudi: { start: '09:00', end: '17:00' },
        Samedi: { start: '10:00', end: '14:00' },
      },
      photos: [],
      status: 'observation',
      trust_score: 4.3,
      review_count: 5,
      parrain_code: 'ROKGU006',
      kory_balance: 10,
      is_talent: true,
      is_admin: false,
      avatar_url: null,
      phone: null,
      whatsapp: null,
      parrain_id: null,
      created_at: '2024-04-10T10:00:00Z',
      updated_at: '2024-06-20T12:00:00Z',
    },
  ],
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default async function CasePage({
  params,
}: {
  params: Promise<{ case: string }>
}) {
  const { case: caseSlug } = await params
  const caseData = getCaseBySlug(caseSlug)

  if (!caseData) {
    notFound()
  }

  // Load real talents from Supabase
  const supabase = await createClient()
  const { data: talentsData } = await supabase
    .from('profiles')
    .select('*')
    .eq('is_talent', true)
    .eq('case_slug', caseSlug)
    .neq('status', 'suspendu')
    .order('trust_score', { ascending: false })

  // Fall back to mock data if no real talents yet
  const talents: Profile[] =
    talentsData && talentsData.length > 0
      ? (talentsData as Profile[])
      : (mockTalentsByCase[caseSlug] ?? mockTalentsByCase.beaute)

  return (
    <div className="min-h-screen bg-cream">
      {/* Hero */}
      <section
        className={`py-12 sm:py-16 border-b border-brown/8 ${caseData.color}`}
        aria-labelledby="case-title"
      >
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Breadcrumb */}
          <nav aria-label="Fil d'Ariane" className="mb-6">
            <ol className="flex items-center gap-2 text-sm text-brown/50">
              <li>
                <Link href="/" className="hover:text-primary transition-colors">
                  Accueil
                </Link>
              </li>
              <li aria-hidden="true">/</li>
              <li>
                <Link href="/#nos-cases" className="hover:text-primary transition-colors">
                  Cases
                </Link>
              </li>
              <li aria-hidden="true">/</li>
              <li className="text-brown font-medium" aria-current="page">
                {caseData.label}
              </li>
            </ol>
          </nav>

          <div className="flex items-center gap-5">
            <span
              className="text-6xl"
              role="img"
              aria-label={caseData.label}
            >
              {caseData.icon}
            </span>
            <div>
              <h1
                id="case-title"
                className="text-3xl sm:text-4xl font-bold font-heading text-brown"
              >
                {caseData.label}
              </h1>
              <p className="text-brown/70 text-lg mt-1">{caseData.description}</p>
            </div>
          </div>
        </div>
      </section>

      {/* Content */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="flex flex-col lg:flex-row gap-8">
          {/* Sidebar — FilterBar */}
          <aside className="lg:w-64 shrink-0">
            <div className="sticky top-4">
              <Suspense fallback={<div className="h-48 rounded-xl bg-gray-100 animate-pulse" />}>
                <FilterBar
                  caseSlug={caseSlug}
                  totalResults={talents.length}
                />
              </Suspense>
            </div>
          </aside>

          {/* Main — Talent grid */}
          <main className="flex-1 min-w-0">
            <div className="flex items-center justify-between mb-6">
              <h2 className="font-semibold text-brown text-lg">
                {talents.length} talent{talents.length !== 1 ? 's' : ''} trouvé{talents.length !== 1 ? 's' : ''}
              </h2>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-5">
              {talents.map((talent) => (
                <TalentCard
                  key={talent.id}
                  talent={talent as Profile & { average_rating?: number }}
                />
              ))}
            </div>
          </main>
        </div>
      </div>
    </div>
  )
}
