export const CASES = [
  {
    slug: 'beaute',
    label: 'Case Beauté',
    icon: '👑',
    description: 'Coiffure, onglerie, maquillage',
    color: 'bg-rose-50 border-rose-200',
    services: [
      'Coiffure (braids, locks, perruques)',
      'Onglerie (gel, résine, nail art)',
      'Maquillage (MUA)',
      'Épilation',
      'Perruques et wigs',
      'Soins capillaires (hydratation, soin protéiné)',
      'Coiffure pour enfants',
      'Coiffure pour mariages/événements',
      'Extensions capillaires',
      'Maquillage de jour',
      'Maquillage soirée/mariage',
      'Body painting',
      'Maquillage artistique',
      'Soins du visage',
      'Épilation au fil',
      'Épilation à la cire',
      'Microblading / sourcils',
      'Manucure simple',
      'Pédicure',
      'Pose de faux ongles',
      'Nail art afro',
      'Traitement/soin des ongles',
    ],
  },
  {
    slug: 'maison',
    label: 'Case Maison',
    icon: '🏠',
    description: 'Montage de meubles, bricolage, déménagement',
    color: 'bg-amber-50 border-amber-200',
    services: [
      'Montage de meubles (IKEA, etc.)',
      'Petit bricolage',
      'Aide au déménagement',
      'Décoration intérieure',
      'Électricité (petits travaux)',
      'Plomberie (petites réparations)',
      'Peinture / ravalement',
      'Pose de rideaux / stores',
      'Jardinage / entretien extérieur',
      'Nettoyage de fin de bail',
      'Grand ménage',
      'Organisation et rangement',
      'Garde d\'animaux à domicile',
      'Petite menuiserie',
      'Assemblage électronique',
      'Réparation d\'appareils',
    ],
  },
  {
    slug: 'couture',
    label: 'Case Couture',
    icon: '🧵',
    description: 'Retouches, création sur-mesure, pagne',
    color: 'bg-purple-50 border-purple-200',
    services: [
      'Retouches vêtements',
      'Création sur-mesure (Wax, Bazin, Pagne)',
      'Couture générale',
      'Broderie',
      'Confection de tenues de cérémonie',
      'Robe de mariée sur-mesure',
      'Tenues traditionnelles africaines',
      'Confection boubou / dashiki',
      'Trousseaux bébé',
      'Couture pour enfants',
      'Apprentissage couture (cours)',
      'Customisation vêtements',
      'Réparation de chaussures',
      'Maroquinerie / sacs',
    ],
  },
  {
    slug: 'saveurs',
    label: 'Case Saveurs',
    icon: '🥘',
    description: 'Chef à domicile, traiteur, batch cooking',
    color: 'bg-orange-50 border-orange-200',
    services: [
      'Chef à domicile',
      'Batch cooking hebdomadaire',
      'Traiteur événementiel',
      'Cours de cuisine',
      'Cuisine sénégalaise',
      'Cuisine ivoirienne',
      'Cuisine camerounaise',
      'Cuisine congolaise',
      'Cuisine guinéenne',
      'Cuisine malienne',
      'Cuisine togolaise / béninoise',
      'Cuisine antillaise',
      'Pâtisserie africaine',
      'Gâteaux de fêtes et mariage',
      'Plats végétariens / vegan africains',
      'Jus naturels et boissons',
      'Pâtisserie française',
      'Préparation repas pour enfants',
      'Service traiteur pour entreprises',
    ],
  },
  {
    slug: 'savoir',
    label: 'Case Savoir',
    icon: '🌍',
    description: 'Cours de langues, soutien scolaire, culture',
    color: 'bg-green-50 border-green-200',
    services: [
      'Soutien scolaire',
      'Cours de langues africaines',
      'Initiation aux instruments',
      'Initiation culturelle',
      'Soutien scolaire primaire',
      'Soutien scolaire collège/lycée',
      'Aide aux devoirs',
      'Cours de mathématiques',
      'Cours de français',
      'Préparation examens (Bac, BTS, etc.)',
      'Cours de bambara',
      'Cours de wolof',
      'Cours de lingala',
      'Cours de malinké',
      'Cours d\'arabe dialectal',
      'Apprentissage du djembé',
      'Cours de danse africaine',
      'Cours de guitare / kora',
      'Initiation à la culture africaine',
      'Cours de programmation / informatique',
      'Coaching scolaire',
    ],
  },
  {
    slug: 'zen',
    label: 'Case Zen',
    icon: '🧘',
    description: 'Bien-être, massages, soins naturels',
    color: 'bg-teal-50 border-teal-200',
    services: [
      'Massages traditionnels',
      'Soins capillaires naturels',
      'Conseils en bien-être',
      'Préparation de produits naturels',
      'Massage balinais',
      'Massage californien',
      'Massage sportif',
      'Massage prénatal',
      'Réflexologie plantaire',
      'Drainage lymphatique',
      'Soin visage à l\'argile',
      'Soin corps au karité',
      'Yoga / méditation',
      'Sophrologie',
      'Naturopathie',
      'Aromathérapie',
      'Préparation de savons artisanaux',
      'Préparation de cosmétiques naturels',
    ],
  },
  {
    slug: 'assistance',
    label: 'Case Assistance',
    icon: '📄',
    description: 'Aide administrative, numérique, rédaction',
    color: 'bg-blue-50 border-blue-200',
    services: [
      'Aide aux dossiers administratifs',
      'Rédaction de courriers',
      'Assistance numérique',
      'Traduction',
      'Accompagnement CAF / allocations',
      'Aide pour la retraite / CNAV',
      'Aide à la création d\'entreprise',
      'Comptabilité / gestion simple',
      'Rédaction de CV et lettres de motivation',
      'Aide à la recherche d\'emploi',
      'Création de site web / e-commerce',
      'Gestion des réseaux sociaux',
      'Retouche photo / graphisme',
      'Traduction arabe-français',
      'Traduction anglais-français',
      'Interprétariat',
    ],
  },
  {
    slug: 'aide-personne',
    label: 'Case Aide à la personne',
    icon: '🤝',
    description: 'Baby-sitting, personnes âgées, tâches ménagères',
    color: 'bg-sky-50 border-sky-200',
    services: [
      'Baby-sitting / garde d\'enfants',
      'Accompagnement de personnes âgées',
      'Aide aux courses',
      'Tâches ménagères / ménage',
      'Aide au repassage',
      'Garde d\'enfants le soir / week-end',
      'Baby-sitting d\'urgence',
      'Crèche / assistante maternelle',
      'Accompagnement médical',
      'Lecture / conversation pour personnes âgées',
      'Aide à la mobilité',
      'Aide à l\'hygiène',
      'Livraison de courses',
      'Préparation de repas pour personnes dépendantes',
      'Assistance post-hospitalisation',
      'Soutien psychologique / écoute',
      'Activités / animations pour seniors',
    ],
  },
]

export const VILLES = [
  // Île-de-France
  'Paris',
  'Boulogne-Billancourt',
  'Saint-Denis',
  'Argenteuil',
  'Montreuil',
  'Versailles',
  'Nanterre',
  'Vitry-sur-Seine',
  'Créteil',
  'Aubervilliers',
  'Île-de-France (autre)',
  // Provence-Alpes-Côte d\'Azur
  'Marseille',
  'Nice',
  'Toulon',
  'Aix-en-Provence',
  'Avignon',
  'Antibes',
  // Auvergne-Rhône-Alpes
  'Lyon',
  'Grenoble',
  'Saint-Étienne',
  'Villeurbanne',
  'Clermont-Ferrand',
  'Chambéry',
  // Occitanie
  'Toulouse',
  'Montpellier',
  'Nîmes',
  'Perpignan',
  // Nouvelle-Aquitaine
  'Bordeaux',
  'Limoges',
  'Poitiers',
  'Pau',
  'Bayonne',
  // Hauts-de-France
  'Lille',
  'Amiens',
  'Roubaix',
  'Tourcoing',
  'Dunkerque',
  // Grand Est
  'Strasbourg',
  'Reims',
  'Metz',
  'Nancy',
  'Mulhouse',
  // Pays de la Loire
  'Nantes',
  'Angers',
  'Le Mans',
  'Saint-Nazaire',
  // Bretagne
  'Rennes',
  'Brest',
  'Quimper',
  'Lorient',
  // Normandie
  'Rouen',
  'Caen',
  'Le Havre',
  // Centre-Val de Loire
  'Tours',
  'Orléans',
  // Bourgogne-Franche-Comté
  'Dijon',
  'Besançon',
  // Corse
  'Ajaccio',
  'Bastia',
  // DOM-TOM
  'Fort-de-France (Martinique)',
  'Pointe-à-Pitre (Guadeloupe)',
  'Cayenne (Guyane)',
  'Saint-Denis (La Réunion)',
  'Mamoudzou (Mayotte)',
  // Autre
  'Autre',
]

export const AVAILABILITY_DAYS = [
  'Lundi',
  'Mardi',
  'Mercredi',
  'Jeudi',
  'Vendredi',
  'Samedi',
  'Dimanche',
]

export const KORY_WELCOME = 10
export const KORY_PARRAINAGE = 3
export const KORY_FREE_SLOTS = 5
